apiVersion: v1
kind: Service
metadata:
  name: checkout
  namespace: ecommerce
  labels:
    app: checkout
    component: ecommerce
spec:
  selector:
    app: checkout
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  type: ClusterIP
