apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - catalog-deployment.yaml
  - catalog-service.yaml
  - checkout-deployment.yaml
  - checkout-service.yaml
