apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base
patches:
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: ecommerce-config
  - path: frontend-patch.yaml
    target:
      kind: Deployment
      name: frontend
  - path: catalog-patch.yaml
    target:
      kind: Deployment
      name: catalog
  - path: checkout-patch.yaml
    target:
      kind: Deployment
      name: checkout
